name: ci

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: read
  packages: read

jobs:

  test:
    container:
      image: ${{ vars.CI_CONTAINER_IMAGE || format('ghcr.io/{0}/calculator-cross:latest', github.repository_owner) }}

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "arm-linux-androideabi", qemu: "qemu-arm",     }
          - { name: "arm-linux-gnueabi",     qemu: "qemu-arm",     }
          - { name: "arm-linux-gnueabihf",   qemu: "qemu-arm",     }
          - { name: "arm-linux-musleabi",    qemu: "qemu-arm",     }
          - { name: "arm-linux-musleabihf",  qemu: "qemu-arm",     }
          - { name: "aarch64-linux-android", qemu: "qemu-aarch64", }
          - { name: "aarch64-linux-gnu",     qemu: "qemu-aarch64", }
          - { name: "aarch64-linux-musl",    qemu: "qemu-aarch64", }
          - { name: "riscv64-linux-android", qemu: "qemu-riscv64", }
          - { name: "riscv64-linux-gnu",     qemu: "qemu-riscv64", }
          - { name: "riscv64-linux-musl",    qemu: "qemu-riscv64", }
          - { name: "i686-linux-android",    qemu: "qemu-i386",    }
          - { name: "i686-linux-gnu",        qemu: "qemu-i386",    }
          - { name: "i686-linux-musl",       qemu: "qemu-i386",    }
          - { name: "x86_64-linux-android",  qemu: "qemu-x86_64",  }
          - { name: "x86_64-linux-gnu",      qemu: "qemu-x86_64",  }
          - { name: "x86_64-linux-musl",     qemu: "qemu-x86_64",  }

    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runs_on }}

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Verify required tools
        shell: bash
        run: |
          set -euo pipefail
          cmake --version
          ninja --version
          ${{ matrix.qemu }} --version

      - name: Configure
        run: cmake -B build -G "Ninja Multi-Config" --toolchain cmake/toolchains/${{ matrix.name }}.cmake

      - name: Build
        run: cmake --build build --config Release

      - name: Test
        run: ${{ matrix.qemu }} -L /usr/${{ matrix.name }} ./build/bin/Release/calculator_tests
