name: ci.android

on: [push, pull_request, workflow_dispatch]

jobs:

  android-tests:

    strategy:
      fail-fast: false
      matrix:
        include:
          - { abi: arm64-v8a   }
          - { abi: armeabi-v7a }
          - { abi: x86         }
          - { abi: x86_64      }
    
    name: ${{ matrix.abi }}
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          build-tools: 33.0.2

      - name: Configure
        run: cmake                                                                \
              -B build                                                            \
              -G "Ninja Multi-Config"                                             \
              --toolchain "$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake" \
              -DANDROID_ABI=${{ matrix.abi }}                                     \
              -DANDROID_PLATFORM=android-21

      - name: Build
        run: cmake --build build --config Release

      - name: Run tests
        run: adb shell build/bin/Release/calculator_tests
